# Generated by Django 5.2.15 on 2026-07-01 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(default='v1', max_length=8)),
                ('k', models.IntegerField(default=1)),
                ('run_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(default=0)),
                ('start', models.FloatField(default=0.0)),
                ('end', models.FloatField(default=0.0)),
                ('text', models.TextField(blank=True, default='')),
                ('category_id', models.CharField(blank=True, max_length=64, null=True)),
                ('subcategory_id', models.CharField(blank=True, max_length=64, null=True)),
                ('tone', models.CharField(blank=True, default='', max_length=32)),
                ('angle', models.CharField(blank=True, default='', max_length=32)),
                ('persona', models.CharField(blank=True, default='', max_length=64)),
                ('categorized', models.BooleanField(default=False)),
                ('clip_path', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ClassifyCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify_mode', models.CharField(default='injection', max_length=16)),
                ('model', models.CharField(default='', max_length=48)),
                ('scope_id', models.IntegerField(default=0)),
                ('input_tokens', models.IntegerField(default=0)),
                ('cache_creation_input_tokens', models.IntegerField(default=0)),
                ('cache_read_input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('cycles', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='pipeline.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('path', models.CharField(max_length=1024)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('duration', models.FloatField(default=0.0)),
                ('n_scenes', models.IntegerField(default=0)),
                ('cut_done', models.BooleanField(default=False)),
                ('classify_done', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pipeline.job')),
            ],
        ),
        migrations.AddField(
            model_name='scene',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='pipeline.video'),
        ),
    ]
